services:
    pages.twig.pages_extension:
        class: Kaikmedia\PagesModule\Twig\PagesExtension
        arguments: ["@session"]
        tags:
            - { name: twig.extension }
    pages.form.type.settings:
        class: Kaikmedia\PagesModule\Form\Type\SettingsType
        tags:
            - { name: form.type, alias: settingsform }
    pages.form.type.page:
        class: Kaikmedia\PagesModule\Form\Type\PageType
        tags:
            - { name: form.type, alias: pageform }
    pages.form.type.pagesfilter:
        class: Kaikmedia\PagesModule\Form\Type\PagesFilterType
        tags:
            - { name: form.type, alias: pagesfilterform }            