services:
    kaikmedia_pages_module.link_container:
        class: Kaikmedia\PagesModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@router"
          - "@kaikmedia_pages_module.access_manager"
          - "@=service('zikula_extensions_module.api.variable').get('KaikmediaPagesModule', 'enablecategorization', true)"
        tags:
          - { name: zikula.link_container }

    kaikmedia_pages_module.access_manager:
        class: Kaikmedia\PagesModule\Security\AccessManager
        arguments: 
          - "@request_stack"
          - "@translator.default"
          - "@zikula_permissions_module.api.permission"

    kaikmedia_pages_module.import_helper:
        class: Kaikmedia\PagesModule\Helper\ImportHelper
        arguments:
          - "@request_stack"
          - "@doctrine.orm.default_entity_manager"
          - "@zikula_extensions_module.api.variable"

    kaikmedia_pages_module.helper.search_helper:
        class: Kaikmedia\PagesModule\Helper\SearchHelper
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@zikula_categories_module.api.category_permission'
          - '@session'
          - "@=service('zikula_extensions_module.api.variable').get('KaikmediaPagesModule', 'enablecategorization', true)"
          - "@kaikmedia_pages_module.access_manager"
        tags:
          - { name: zikula.searchable_module, bundleName: KaikmediaPagesModule}